// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMdCkawu-XRPwdJwmE6Vivs4z90Al93no',
    appId: '1:841039182591:web:abd49b8197f6869cbdaaca',
    messagingSenderId: '841039182591',
    projectId: 'car-zone-e3779',
    authDomain: 'car-zone-e3779.firebaseapp.com',
    storageBucket: 'car-zone-e3779.firebasestorage.app',
    measurementId: 'G-J6D6NKZ0TW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFs4_q3zgkLUPsQTRJTyTc4Rl4qIvDBBs',
    appId: '1:841039182591:android:cad667bbe934cadbbdaaca',
    messagingSenderId: '841039182591',
    projectId: 'car-zone-e3779',
    storageBucket: 'car-zone-e3779.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAraqbYLmOkWxkvKY_Ioca-d4cGK2_PnSw',
    appId: '1:841039182591:ios:ddcb826cb0242aedbdaaca',
    messagingSenderId: '841039182591',
    projectId: 'car-zone-e3779',
    storageBucket: 'car-zone-e3779.firebasestorage.app',
    iosBundleId: 'com.example.carZone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAraqbYLmOkWxkvKY_Ioca-d4cGK2_PnSw',
    appId: '1:841039182591:ios:ddcb826cb0242aedbdaaca',
    messagingSenderId: '841039182591',
    projectId: 'car-zone-e3779',
    storageBucket: 'car-zone-e3779.firebasestorage.app',
    iosBundleId: 'com.example.carZone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMdCkawu-XRPwdJwmE6Vivs4z90Al93no',
    appId: '1:841039182591:web:a41d7abce9871897bdaaca',
    messagingSenderId: '841039182591',
    projectId: 'car-zone-e3779',
    authDomain: 'car-zone-e3779.firebaseapp.com',
    storageBucket: 'car-zone-e3779.firebasestorage.app',
    measurementId: 'G-E0FG8F7YSM',
  );
}
